// sites/next.skeleton.dev/src/examples/components/navigation/Example.tsx
import React from 'react';
import { Navigation } from '@skeletonlabs/skeleton-react';
import {
	Menu as IconMenu,
	Folder as IconFolder,
	Image as IconImage,
	Music as IconMusic,
	Video as IconVideo,
	Settings as IconSettings
} from 'lucide-react';

export const Page: React.FC = () => {
	return (
		<div className="card border-surface-100-900 grid h-[640px] w-full grid-cols-[auto_1fr] border-[1px]">
			{/* Component */}
			{/* prettier-ignore */}
			<Navigation.Rail
				header={<Navigation.Tile id="0" href="/" title="Menu"><IconMenu /></Navigation.Tile>}
				footer={<Navigation.Tile id="1" href="/settings" title="settings"><IconSettings /></Navigation.Tile>}
			>
				<Navigation.Tile id="2" label="Files" href="#"><IconFolder /></Navigation.Tile>
				<Navigation.Tile id="3" label="Images" href="#"><IconImage /></Navigation.Tile>
				<Navigation.Tile id="4" label="Music" href="#"><IconMusic /></Navigation.Tile>
				<Navigation.Tile id="5" label="Videos" href="#"><IconVideo /></Navigation.Tile>
			</Navigation.Rail>
			{/* Content */}
			<div className="flex items-center justify-center">
				<p className="opacity-20">(Content)</p>
			</div>
		</div>
	);
};

// sites/next.skeleton.dev/src/examples/components/navigation/Example.svelte
<script lang="ts">
	import { Navigation } from '@skeletonlabs/skeleton-svelte';
	// Icons
	import IconMenu from 'lucide-svelte/icons/menu';
	import IconFolder from 'lucide-svelte/icons/folder';
	import IconImage from 'lucide-svelte/icons/image';
	import IconMusic from 'lucide-svelte/icons/music';
	import IconVideo from 'lucide-svelte/icons/video';
	import IconSettings from 'lucide-svelte/icons/settings';

	let hrefExample = '#';
</script>

<div class="card border-surface-100-900 grid h-[640px] w-full grid-cols-[auto_1fr] border-[1px]">
	<!-- Component -->
	<Navigation.Rail>
		{#snippet header()}
			<Navigation.Tile id="0" href="/" title="Menu"><IconMenu /></Navigation.Tile>
		{/snippet}
		{#snippet tiles()}
			<Navigation.Tile id="1" label="Files" href={hrefExample}>
				<IconFolder />
			</Navigation.Tile>
			<Navigation.Tile id="2" label="Images" href={hrefExample}>
				<IconImage />
			</Navigation.Tile>
			<Navigation.Tile id="3" label="Music" href={hrefExample}>
				<IconMusic />
			</Navigation.Tile>
			<Navigation.Tile id="4" label="Videos" href={hrefExample}>
				<IconVideo />
			</Navigation.Tile>
		{/snippet}
		{#snippet footer()}
			<Navigation.Tile id="5" labelExpanded="Settings" href="/settings" title="settings"><IconSettings /></Navigation.Tile>
		{/snippet}
	</Navigation.Rail>
	<!-- Content -->
	<div class="flex items-center justify-center">
		<p class="opacity-20">(Content)</p>
	</div>
</div>
